
name: syntax
on: push
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-c@v2
        with:
          c-latest
      - run: echo Tester is working
      - run: gcc -v
      - run: python src/main.c
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-c@v2
        with:
          c-latest
      - run: echo Tester is working
      - run: python src/main.c
  
